feat: Allow local certificates to be used by Caddy
dunglas/symfony-docker pull request #106
Opened 2021-01-13 12:24 UTC by thePanz

2021-01-13 12:59 UTC, B-Galati commented
Great! Thank you @thePanz :pray:

2021-01-13 14:48 UTC, dunglas commented
Awesome! As it's a relatively specific use case, I would prefer to not add too much "unnecessary" comments to the skeleton itself. Could we just add a doc entry explaining what lines to add as we've done for XDebug? We can use the ` ```patch ` Markdown trick for this purpose.

2021-01-16 11:39 UTC, maxhelias commented
Wow! Thanks @thePanz  🎉 

@dunglas, maybe rework the xdebug part to have only one page on development options (xdebug + tls)

2021-01-16 17:00 UTC, dunglas commented
@maxhelias, I'm not sure. I think having small pages with descriptive URLs and titles will improve SEO.

2021-07-23 18:11 UTC, zmitic commented
After many hours, I failed to make it work. My setup is Linux mint, and all I get is non-responsive page.

Troubleshooting page with ``docker cp`` command also doesn't work, even with changed path (usr/share instead of usr/local/share).

I am out of ideas.

2021-12-29 21:23 UTC, mfehr94 commented
@zmitic the problem is the `caddy:80` in `SERVER_NAME="api.localhost, caddy:80"`. It is not possible to configure tls on sites that listen on the HTTP port.

@thePanz @maxhelias @dunglas any suggestions to solve this issue?

2022-01-12 13:28 UTC, Jayfrown commented
Thanks, I got it to work as follows:

```diff
❯ git diff --staged | cat        
diff --git a/docker-compose.override.yml b/docker-compose.override.yml
index 0143fec..2ab2b3d 100644
--- a/docker-compose.override.yml
+++ b/docker-compose.override.yml
@@ -17,6 +17,10 @@ services:
     volumes:
       - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
       - ./public:/srv/app/public:ro
+      - ./docker/caddy/certs:/etc/caddy/certs:ro
+    environment:
+      SERVER_NAME: ${SERVER_NAME:-localhost, caddy}
+      CADDY_TLS_CONFIG: "tls /etc/caddy/certs/tls.pem /etc/caddy/certs/tls.key"
 
   phpldapadmin:
     image: osixia/phpldapadmin:latest
diff --git a/docker-compose.yml b/docker-compose.yml
index c1a1ea9..044033f 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -20,7 +20,7 @@ services:
       start_period: 30s
     environment:
       DATABASE_URL: "mysqli://root:${MYSQL_ROOT_PASSWORD:-!ChangeMe!}@database:3306/${MYSQL_DATABASE:-app}?serverVersion=mariadb-10.3.13"
-      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
+      MERCURE_URL: ${CADDY_MERCURE_URL:-https://caddy/.well-known/mercure}
       MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
       MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
       JWT_PASSPHRASE: ${JWT_PASSPHRASE:-!ChangeMe!}
diff --git a/docker/caddy/Caddyfile b/docker/caddy/Caddyfile
index 6d5387c..18f70c3 100644
--- a/docker/caddy/Caddyfile
+++ b/docker/caddy/Caddyfile
@@ -11,6 +11,8 @@
 
 {$SERVER_NAME}
 
+{$CADDY_TLS_CONFIG}
+
 log
 
 route {
diff --git a/docker/caddy/certs/.gitignore b/docker/caddy/certs/.gitignore
new file mode 100644
index 0000000..65e3d29
--- /dev/null
+++ b/docker/caddy/certs/.gitignore
@@ -0,0 +1,3 @@
+# Ignore locally generated certs for Caddy
+tls.key
+tls.pem
```

I added the `.gitignore` because in a multi-developer project you would want everyone to have their own locally generated CA and certs.

---

Now caddy uses the locally generated certificates, which means the cert is trusted within my browser. However, the CA generated by `mkcert` is apparently not automatically trusted in my local PHP set-up, so local commands that try to send Mercure updates still fail as follows:

```
SSL certificate problem: unable to get local issuer certificate for "https://localhost/.well-known/mercure".
```

As the CA is now (relatively) static I can add it to the trust store used by PHP as follows:

```
cat "$(mkcert -CAROOT)/rootCA.pem" >> /usr/local/etc/openssl@1.1/cert.pem
```

Note that this might be a MacOS / brew PHP specific issue. Can someone confirm/refute whether the CA generated by `mkcert` is automatically trusted in local PHP when run on Linux?

2022-01-12 14:33 UTC, Jayfrown commented
Both issues could be fixed if there is a separate configuration within the Caddyfile for caddy:80 and localhost:443, such that both local PHP and the docker PHP app can send updates to `http://caddy/.well-known/mercure` (as is the default for the dockerized PHP app). The stanza for localhost:443 could then use the certs generated by `mkcert`.

2022-06-23 06:17 UTC, mario-fehr commented
Any plans to fix and merger this?

2022-10-18 11:38 UTC, maxhelias commented
I updated this PR

2022-10-18 11:42 UTC, thePanz commented
Thanks @maxhelias for the update, sorry for not following up on this :+1:

2022-10-25 11:59 UTC, dunglas commented
This looks good to me.
@mholt would you mind checking if it's in sync with Caddy's best practices?

2022-10-25 12:10 UTC, dunglas requested changes

2022-10-25 12:10 UTC, dunglas commented on docs/tls.md
> +You must copy it and add it to the trusted certificates :
```suggestion
You must add the authority to the trust store of the host:
```

2022-10-25 12:10 UTC, dunglas commented on docker/caddy/Caddyfile
> +{$CADDY_TLS_CONFIG}
```suggestion
{$CADDY_EXTRA_CONFIG}
```

As this may have other uses.

2022-10-25 12:10 UTC, dunglas commented on docs/tls.md
> +With a basic installation, the self-signed certificate from caddy is not know by your local machine.
```suggestion
With a standard installation, the authority used to sign certificates generated in the Caddy container is not trusted by your local machine. 
```

2022-10-25 12:10 UTC, dunglas commented on docs/tls.md
> +## Using caddy TLS certificates
```suggestion
## Trusting the Authority
```

2022-10-25 12:10 UTC, dunglas commented on docs/tls.md
> +## Using local TLS certificates
```suggestion
## Using Custom TLS Certificates
```

2022-10-25 12:10 UTC, dunglas commented on docs/tls.md
> +Caddy is configured to generate TLS certificates by using Let's Encrypt, but for local deployments this does not work,
```suggestion
By default, Caddy will automatically generate TLS certificates using Let's Encrypt or ZeroSSL.
```

2022-10-25 12:10 UTC, dunglas commented on docs/tls.md
> +and the internal caddy certificate should be imported locally (see above).
```suggestion
But sometimes you may prefer using custom certificates.
```

2022-10-25 12:10 UTC, dunglas commented on docs/tls.md
> +To use local certificates created with [mkcert](https://github.com/FiloSottile/mkcert) do as follows:
```suggestion
For instance, to use self-signed certificates created with [mkcert](https://github.com/FiloSottile/mkcert) do as follows:
```

2022-10-25 12:10 UTC, dunglas commented on docs/tls.md
> +    +    CADDY_TLS_CONFIG: "tls /etc/caddy/certs/tls.pem /etc/caddy/certs/tls.key"
```suggestion
    +    CADDY_EXTRA_CONFIG: "tls /etc/caddy/certs/tls.pem /etc/caddy/certs/tls.key"
```

2022-10-25 12:10 UTC, dunglas commented on docs/troubleshooting.md
> +## TLS trust issues
```suggestion
## TLS/HTTPS Issues
```

2022-10-28 15:28 UTC, mholt approved these changes
I think that looks good overall!

The only thing is that we pretty much always recommend letting Caddy manage the certificates, instead of using external tools or certs, whenever possible. (It should almost always be possible to use Caddy's certs these days, even if you need a custom CA or something.)

2022-11-25 13:36 UTC, merged