docs: add all options available with env var
dunglas/symfony-docker pull request #598
Opened 2024-04-05 15:44 UTC by maxhelias

Fix #532

2024-04-05 18:22 UTC, dunglas requested changes

2024-04-05 18:22 UTC, dunglas commented on docs/options.md
> +# Caddyfile Options
```suggestion
## Caddyfile Options
```

2024-04-05 21:40 UTC, dunglas approved these changes
Awesome!

2024-04-06 02:51 UTC, maxhelias commented on docs/options.md
> +## Example of server name customize:
```suggestion
### Example of server name customize:
```

2024-04-06 02:53 UTC, merged