Add a line at the end of docker-entrypoint to indicate that work is done
dunglas/symfony-docker pull request #703
Opened 2024-11-26 16:00 UTC by tcoch

**Problem statement :**
When running docker compose, for a few seconds / minutes, the container is running according to Docker, but in fact `docker-entrypoint.sh` is still downloading composer requirements and handling migrations. During this time, the app is not available. This means functionnal tests will fail if launched too early.

**Solution proposed :**
This pull requests aims to simply add a logging line at the end of `docker-enntrypoint.sh`, to provide a standard log that can be watched by dev / devops teams. A `grep` on docker logs will make people aware that : "ok, dependencies should be installed by now, so my app should be working".

2024-11-26 16:35 UTC, dunglas requested changes
Good idea, what do you think about a more simple message?

2024-11-26 16:35 UTC, dunglas commented on frankenphp/docker-entrypoint.sh
> +	echo 'Entrypoint has finished its work !'
```suggestion
	echo 'PHP app ready!'
```

2024-11-27 08:33 UTC, maxhelias approved these changes

2024-11-27 14:23 UTC, dunglas approved these changes

2024-11-27 14:24 UTC, merged

2024-11-27 14:24 UTC, dunglas commented
Thanl you